### ISSUE TITLE
Provide predetermined position data structure as entrypoint argument

### ISSUE THREAD

**Issue by jmlane** [jmlane/force-deployment#2]
There needs to be some sort of data structure that demonstrates ORBAT and position data for redeploying a previously deployed force.

This will give us a quick way to do a fake persistence for the MVP, since we can store this data structure persistently and initialize a map with pre-calculated position data.

Example structure for discussion:
```sqf
_orbat = [
	["BN", pos, [
		["COY", pos, [
			["PL", pos],
			["PL", pos],
			["PL", pos]
		]],
		["COY", pos, [
			["PL", pos],
			["PL", pos],
			["PL", pos]
		]],
		["COY", pos, [
			["PL", pos],
			["PL", pos],
			["PL", pos]
		]]
	]]
];
```

**Comment by jmlane** [comment]
@Diffusion9 @DEL-J What do you folks think? This looks like it will serve our initial purpose but we should discuss something that could easily be expanded to provide extra data about the strength and disposition of each formation.

Might be worth looking at how KillzoneKid, CBA3, ACE3 et al. fake dictionaries.

**Comment by Diffusion9** [comment]
Initial thoughts: I'm not against doing it dirty and just using multidimensional arrays for now. I'm sure KK and those folks have fancy ways, but unless you're willing, I can't really be arsed to learn them right now with all the other things going on.

We could reduce the array size by not storing the PL positions. Do we necessarily need to be that granular with their persistence position? It might matter once-in-a-blue-moon, but i think just saving the BN and COY positions and spawning the PLs around those positions either at random (or selectively in formation) would be fine.

**Comment by jmlane** [comment]
Agreed, I think nested arrays is the way to go for now.

I could go either way on storing PL position for persistence, simply because it doesn't really make a big difference from an implementation perspective. If the design goal would be to *never* persist between mission start-ups, it's easy to omit.

What does @DEL-J have to say?

**Comment by DEL-J** [comment]
I'm too ignorant of how this works. If we have the chance to chat this out, we should.
