### ISSUE TITLE
Composition waypoint handling incomplete

### ISSUE THREAD

**Issue by jmlane** [jmlane/force-deployment#7]
@DEL-J's compositions with waypoints have exposed an issue with the third-party composition spawning script we are using.

Log:
```
3:27:16 Error in expression <s;
_wp setWaypointCombatMode _mode;
_wp setWaypointFormation _formation;
_wp set>
 3:27:16   Error position: <setWaypointFormation _formation;
_wp set>
 3:27:16   Error Foreign error: Unknown enum value: ""
 3:27:16 File LARs\functions\fn_createComp.sqf [LARs_fnc_createComp], line 1202
```

**Comment by jmlane** [comment]
It's my recommendation that we fork the composition spawning script and fix issues or gap-fill any missing functionality.

[It seems the author is no longer supporting the script and has been unresponsive on the official thread for over a year now](https://forums.bohemia.net/forums/topic/191902-eden-composition-spawning/).

**Comment by Diffusion9** [comment]
Agreed. Useful, and likely worth maintaining. Not worth reinventing the wheel. Not a fun wheel to reinvent anyways.

**Comment by jmlane** [comment]
https://github.com/jmlane/SimTools-Compositions will cover the forked scripts.
